// Mock data for the dashboard
import { ProposedQuestion, Question, Answer, KPIStat, ConnectorHealth, Source, AuditEvent, Agent } from './types';

export const mockSources: Source[] = [
  {
    id: 's1',
    type: 'twitter',
    url: 'https://twitter.com/user/status/123',
    title: 'Thread about AI capabilities',
    outlet: 'Twitter',
    trustLevel: 'medium',
    fetchedAt: new Date('2025-10-08T10:00:00Z'),
    content: 'Recent developments in AI suggest...',
    isPinned: true,
  },
  {
    id: 's2',
    type: 'news',
    url: 'https://techcrunch.com/article',
    title: 'Major breakthrough in quantum computing',
    outlet: 'TechCrunch',
    trustLevel: 'high',
    fetchedAt: new Date('2025-10-07T15:30:00Z'),
    content: 'Scientists announced a major advancement...',
  },
  {
    id: 's3',
    type: 'meme',
    url: 'https://reddit.com/r/memes/post',
    title: 'Viral meme about market trends',
    outlet: 'Reddit',
    trustLevel: 'low',
    fetchedAt: new Date('2025-10-06T20:15:00Z'),
    content: 'Popular meme showing...',
  },
];

export const mockProposedQuestions: ProposedQuestion[] = [
  {
    id: 'pq1',
    title: 'Will OpenAI release GPT-5 before the end of 2025?',
    description: 'This question asks whether OpenAI will officially announce and release GPT-5 to the public before December 31, 2025. The resolution will be based on official announcements from OpenAI and verified release documentation.',
    liveDate: new Date('2025-10-28T15:00:00Z'),
    proposedAnswerEndAt: new Date('2025-12-15T23:59:59Z'),
    proposedSettlementAt: new Date('2026-01-05T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if OpenAI publicly announces GPT-5 with general availability before Dec 31, 2025. Resolves NO otherwise.',
    sources: [mockSources[0], mockSources[1]],
    aiScore: 0.95,
    riskFlags: [],
    createdAt: new Date('2025-10-09T08:00:00Z'),
    categories: ['Technology', 'AI'],
    type: 'binary',
  },
  {
    id: 'pq2',
    title: 'Will Bitcoin exceed $100,000 in October 2025?',
    description: 'This question asks whether Bitcoin\'s price will reach or exceed $100,000 USD at any point during October 2025. The price will be determined based on major cryptocurrency exchanges including Coinbase, Binance, and Kraken.',
    liveDate: new Date('2025-10-28T16:00:00Z'),
    proposedAnswerEndAt: new Date('2025-10-25T23:59:59Z'),
    proposedSettlementAt: new Date('2025-11-01T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if Bitcoin trades at or above $100,000 on any major exchange during October 2025.',
    sources: [mockSources[1], mockSources[2]],
    aiScore: 0.92,
    riskFlags: [],
    createdAt: new Date('2025-10-08T14:30:00Z'),
    categories: ['Cryptocurrency', 'Finance'],
    type: 'binary',
  },
  {
    id: 'pq3',
    title: 'Will the S&P 500 close above 6000 by year end?',
    description: 'This question asks whether the S&P 500 index will close above 6000 points by December 31, 2025. Resolution will be based on the official closing price on the last trading day of 2025 as reported by major financial data providers.',
    liveDate: new Date('2025-10-29T14:00:00Z'),
    proposedAnswerEndAt: new Date('2025-12-20T23:59:59Z'),
    proposedSettlementAt: new Date('2026-01-02T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if the S&P 500 closes above 6000 on its last trading day of 2025.',
    sources: [mockSources[0]],
    aiScore: 0.88,
    riskFlags: [],
    createdAt: new Date('2025-10-07T11:00:00Z'),
    categories: ['Finance', 'Markets'],
    type: 'multi-option',
  },
  {
    id: 'pq4',
    title: 'Will Apple Vision Pro 2 launch before June 2026?',
    description: 'This question asks whether Apple will officially launch the second generation of Vision Pro headset before June 30, 2026. The resolution will be based on official Apple announcements and product availability.',
    liveDate: new Date('2025-10-30T13:00:00Z'),
    proposedAnswerEndAt: new Date('2026-05-31T23:59:59Z'),
    proposedSettlementAt: new Date('2026-06-15T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if Apple officially launches Vision Pro 2 with general availability before June 30, 2026.',
    sources: [mockSources[1]],
    aiScore: 0.84,
    riskFlags: [],
    createdAt: new Date('2025-10-07T09:00:00Z'),
    categories: ['Technology', 'Apple'],
    type: 'binary',
  },
  {
    id: 'pq5',
    title: 'Will Ethereum implement EIP-7691 before Q2 2026?',
    description: 'This question asks whether the Ethereum network will successfully implement Ethereum Improvement Proposal 7691 before the end of Q2 2026. The resolution will be based on official Ethereum Foundation announcements and on-chain verification.',
    liveDate: new Date('2025-10-28T17:00:00Z'),
    proposedAnswerEndAt: new Date('2026-06-15T23:59:59Z'),
    proposedSettlementAt: new Date('2026-06-30T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if EIP-7691 is successfully implemented on Ethereum mainnet before June 30, 2026.',
    sources: [mockSources[0], mockSources[2]],
    aiScore: 0.79,
    riskFlags: [],
    createdAt: new Date('2025-10-06T16:00:00Z'),
    categories: ['Cryptocurrency', 'Technology'],
    type: 'multi-option',
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    title: 'Will Bitcoin hit $120k in November 2025?',
    description: 'This question asks whether Bitcoin will reach or exceed $120,000 USD at any point during November 2025. The price will be determined based on major cryptocurrency exchanges including Coinbase, Binance, and Kraken.',
    state: 'published',
    answerEndAt: new Date('2025-11-30T23:59:59Z'),
    settlementAt: new Date('2025-12-05T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if Bitcoin trades at or above $120,000 on any major exchange during November 2025. Resolves NO otherwise.',
    categories: ['Cryptocurrency', 'Finance'],
    topic: 'Cryptocurrency Markets',
    sources: [mockSources[0], mockSources[1]],
    answerCount: 342,
    createdAt: new Date('2025-10-15T10:00:00Z'),
    updatedAt: new Date('2025-10-20T14:20:00Z'),
    assignee: 'admin@example.com',
    type: 'Binary',
    tags: ['crypto', 'bitcoin', 'price'],
    poolSize: {
      total: 15800,
      yes: 9200,
      no: 6600,
    },
    createdBy: 'Travis',
  },
  {
    id: 'q2',
    title: 'Will Apple announce a new iPhone model in September 2025?',
    description: 'This question resolves based on whether Apple holds an event announcing new iPhone models in September 2025.',
    state: 'awaiting_resolution',
    answerEndAt: new Date('2025-09-30T23:59:59Z'),
    settlementAt: new Date('2025-10-05T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if Apple officially announces at least one new iPhone model in September 2025.',
    categories: ['Technology', 'Apple'],
    topic: 'Consumer Electronics',
    sources: [mockSources[1]],
    answerCount: 127,
    createdAt: new Date('2025-08-01T10:00:00Z'),
    updatedAt: new Date('2025-08-15T14:20:00Z'),
    assignee: 'admin@example.com',
    type: 'Binary',
    tags: ['tech', 'apple', 'iphone'],
    poolSize: {
      total: 9200,
      yes: 7400,
      no: 1800,
    },
    createdBy: 'Travis',
  },
  {
    id: 'q3',
    title: 'Will Ethereum switch to a new consensus mechanism in 2025?',
    description: 'This question asks whether Ethereum will implement a major change to its consensus mechanism during 2025.',
    state: 'awaiting_resolution',
    answerEndAt: new Date('2025-10-01T23:59:59Z'),
    settlementAt: new Date('2025-10-08T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if Ethereum Foundation officially implements a new consensus mechanism in 2025.',
    categories: ['Cryptocurrency', 'Technology'],
    sources: [mockSources[0], mockSources[1]],
    answerCount: 89,
    createdAt: new Date('2025-07-15T09:00:00Z'),
    updatedAt: new Date('2025-09-20T16:45:00Z'),
    type: 'Binary',
    tags: ['crypto', 'ethereum', 'blockchain'],
    poolSize: {
      total: 5600,
      yes: 3200,
      no: 2400,
    },
    createdBy: 'Sarah',
  },
  {
    id: 'q4',
    title: 'Will Tesla stock split in Q4 2025?',
    description: 'This question asks whether Tesla will announce and execute a stock split in Q4 2025.',
    state: 'paused',
    answerEndAt: new Date('2025-12-15T23:59:59Z'),
    settlementAt: new Date('2025-12-31T23:59:59Z'),
    resolutionCriteria: 'Resolves YES if Tesla announces and completes a stock split between Oct 1 and Dec 31, 2025.',
    categories: ['Finance', 'Stocks'],
    reviewStatus: 'pending',
    sources: [mockSources[2]],
    answerCount: 0,
    createdAt: new Date('2025-10-05T13:00:00Z'),
    updatedAt: new Date('2025-10-06T10:30:00Z'),
    assignee: 'moderator@example.com',
    type: 'Binary',
    tags: ['finance', 'stocks', 'tesla'],
    poolSize: {
      total: 0,
      yes: 0,
      no: 0,
    },
    createdBy: 'Travis',
  },
];

export const mockAnswers: Answer[] = [
  {
    id: 'a1',
    questionId: 'q1',
    questionTitle: 'Will Bitcoin hit $120k in November 2025?',
    userId: 'u1',
    userName: 'Alice Johnson',
    choice: 'YES',
    confidence: 0.85,
    placedAt: new Date('2025-10-20T14:30:00Z'),
    channel: 'web',
  },
  {
    id: 'a2',
    questionId: 'q1',
    questionTitle: 'Will Bitcoin hit $120k in November 2025?',
    userId: 'u2',
    userName: 'Bob Smith',
    choice: 'YES',
    confidence: 0.72,
    placedAt: new Date('2025-10-21T10:15:00Z'),
    channel: 'mobile',
  },
  {
    id: 'a3',
    questionId: 'q2',
    questionTitle: 'Will Apple announce a new iPhone model in September 2025?',
    userId: 'u3',
    userName: 'Carol White',
    choice: 'YES',
    confidence: 0.90,
    placedAt: new Date('2025-09-15T14:30:00Z'),
    channel: 'web',
  },
  {
    id: 'a4',
    questionId: 'q2',
    questionTitle: 'Will Apple announce a new iPhone model in September 2025?',
    userId: 'u4',
    userName: 'David Lee',
    choice: 'NO',
    confidence: 0.65,
    placedAt: new Date('2025-09-16T10:15:00Z'),
    channel: 'mobile',
  },
  {
    id: 'a5',
    questionId: 'q3',
    questionTitle: 'Will Ethereum switch to a new consensus mechanism in 2025?',
    userId: 'u5',
    userName: 'Emma Davis',
    choice: 'YES',
    confidence: 0.75,
    placedAt: new Date('2025-09-20T16:45:00Z'),
    channel: 'web',
  },
];

export const mockKPIs: KPIStat[] = [
  { label: 'Drafts', value: 12, trend: 'up', change: 3 },
  { label: 'Awaiting Review', value: 5, trend: 'neutral' },
  { label: 'Published Open', value: 23, trend: 'up', change: 5 },
  { label: 'Awaiting Resolution', value: 8, trend: 'down', change: -2 },
  { label: 'Overdue', value: 2, trend: 'down', change: -1 },
  { label: 'Scored This Week', value: 15, trend: 'up', change: 7 },
];

export const mockConnectors: ConnectorHealth[] = [
  {
    id: 'c1',
    name: 'Twitter Accounts',
    type: 'twitter',
    lastRun: new Date('2025-10-09T08:00:00Z'),
    status: 'healthy',
    itemsIngested: 1247,
    failureCount: 0,
  },
  {
    id: 'c2',
    name: 'News Aggregator',
    type: 'news',
    lastRun: new Date('2025-10-09T07:30:00Z'),
    status: 'healthy',
    itemsIngested: 543,
    failureCount: 2,
  },
  {
    id: 'c3',
    name: 'Reddit',
    type: 'meme',
    lastRun: new Date('2025-10-09T06:45:00Z'),
    status: 'warning',
    itemsIngested: 89,
    failureCount: 15,
  },
];

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'ae1',
    timestamp: new Date('2025-10-09T10:30:00Z'),
    actor: 'admin@example.com',
    action: 'question.published',
    entityType: 'question',
    entityId: 'q1',
    changes: { state: { from: 'draft', to: 'published' } },
  },
  {
    id: 'ae2',
    timestamp: new Date('2025-10-09T09:15:00Z'),
    actor: 'moderator@example.com',
    action: 'suggestion.approved',
    entityType: 'suggestion',
    entityId: 'pq1',
  },
  {
    id: 'ae3',
    timestamp: new Date('2025-10-08T16:20:00Z'),
    actor: 'admin@example.com',
    action: 'question.resolved',
    entityType: 'question',
    entityId: 'q2',
    changes: { outcome: { from: null, to: 'YES' } },
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'agent1',
    name: 'Elon Market Agent',
    description: 'Creates prediction markets based on Elon Musk\'s latest tweets',
    sources: [
      {
        type: 'x',
        config: {
          url: 'https://x.com/elonmusk',
        },
      },
    ],
    questionPrompt: 'Create a question based on Elon Musk\'s latest tweet',
    resolutionPrompt: 'Answer the question by researching the web and finding the answer.',
    frequency: 'on_update',
    status: 'active',
    questionsCreated: 47,
    lastRun: new Date('2025-10-28T08:30:00Z'),
    nextRun: new Date('2025-10-28T12:00:00Z'),
    createdAt: new Date('2025-09-15T10:00:00Z'),
    updatedAt: new Date('2025-10-28T08:30:00Z'),
    isTemplate: true,
  },
  {
    id: 'agent2',
    name: 'r/Futurology Agent',
    description: 'Creates statistical questions about trending posts from r/Futurology',
    sources: [
      {
        type: 'reddit',
        config: {
          subreddit: 'Futurology',
        },
      },
    ],
    questionPrompt: 'Create a statistical question about the latest posts from the subreddit',
    resolutionPrompt: 'Answer the question by researching the web and finding the answer.',
    frequency: 'daily',
    status: 'active',
    questionsCreated: 23,
    lastRun: new Date('2025-10-28T06:00:00Z'),
    nextRun: new Date('2025-10-29T06:00:00Z'),
    createdAt: new Date('2025-09-20T14:00:00Z'),
    updatedAt: new Date('2025-10-28T06:00:00Z'),
    isTemplate: true,
  },
  {
    id: 'agent3',
    name: 'Price Feed Agent',
    description: 'Creates price prediction markets for tokens using real-time data feeds',
    sources: [
      {
        type: 'feed',
        config: {
          feedUrl: 'https://feed.com/api/123/token',
        },
      },
    ],
    questionPrompt: 'Create a question about this token\'s price within the next month. For example: Will $TOKEN reach $X in November?',
    resolutionPrompt: 'Determine the answer by viewing the historical numbers from this feed https://feed.com/api/123/token',
    frequency: 'weekly',
    status: 'active',
    questionsCreated: 12,
    lastRun: new Date('2025-10-27T10:00:00Z'),
    nextRun: new Date('2025-11-03T10:00:00Z'),
    createdAt: new Date('2025-10-01T09:00:00Z'),
    updatedAt: new Date('2025-10-27T10:00:00Z'),
    isTemplate: true,
  },
  {
    id: 'agent4',
    name: 'Bitcoin Price Agent',
    description: 'Creates daily YES/NO prediction markets about Bitcoin closing prices',
    sources: [
      {
        type: 'api',
        config: {
          apiEndpoint: 'https://theanomaly.app.n8n.cloud/webhook/getbtcdata?ticker=btc',
        },
      },
    ],
    questionPrompt: 'Generate a question YES/NO Prediction: One asking whether the asset will close **above** today’s price. Keep the questions simple and direct for a prediction market betting app. Only return the text of the questions, no preamble or explanation.',
    resolutionPrompt: 'Answer the question by researching the web and finding the answer.',
    frequency: 'daily',
    status: 'active',
    questionsCreated: 34,
    lastRun: new Date('2025-10-28T07:00:00Z'),
    nextRun: new Date('2025-10-29T07:00:00Z'),
    createdAt: new Date('2025-09-10T11:00:00Z'),
    updatedAt: new Date('2025-10-28T07:00:00Z'),
  },
  {
    id: 'agent5',
    name: 'AIXBT News',
    description: 'Monitors AIXBT news and creates relevant prediction markets',
    sources: [
      {
        type: 'x',
        config: {
          url: 'https://x.com/aixbt_agent',
        },
      },
    ],
    questionPrompt: 'Create a question about AIXBT latest tweets',
    resolutionPrompt: 'Answer the question by researching the web and finding the answer.',
    frequency: 'daily',
    status: 'active',
    questionsCreated: 21,
    lastRun: new Date('2025-10-28T07:00:00Z'),
    nextRun: new Date('2025-10-29T07:00:00Z'),
    createdAt: new Date('2025-09-10T11:00:00Z'),
    updatedAt: new Date('2025-10-28T07:00:00Z'),
  },
];