import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function seedBTCAgent() {
  console.log('🌱 Seeding Bitcoin Price Feed Agent...');

  try {
    // Create the Bitcoin Price Feed Agent
    const agent = await prisma.agent.create({
      data: {
        id: 'agent4',
        name: 'Price Feed Agent',
        description: 'Monitors cryptocurrency price feeds and creates prediction questions about future price movements',
        category: 'Finance',
        questionPrompt: "Generate a question YES/NO Prediction: One asking whether the asset will close **above** today's price. Keep the questions simple and direct for a prediction market betting app. Only return the text of the questions, no preamble or explanation.",
        resolutionPrompt: 'Answer the question by researching the web and finding the answer.',
        baseModel: 'chatgpt-4o-latest',
        frequency: 'on_update',
        status: 'active',
        questionsCreated: 34,
        lastRun: new Date('2025-10-28T07:00:00Z'),
        nextRun: new Date('2025-10-29T07:00:00Z'),
        createdAt: new Date('2025-09-10T11:00:00Z'),
        updatedAt: new Date('2025-10-28T07:00:00Z'),
      },
    });

    console.log('✅ Created agent:', agent.name);

    // Create the agent source (API endpoint)
    const agentSource = await prisma.agentSource.create({
      data: {
        agentId: agent.id,
        type: 'api',
        configApiEndpoint: 'https://theanomaly.app.n8n.cloud/webhook/getbtcdata?ticker=btc',
        createdAt: new Date('2025-09-10T11:00:00Z'),
      },
    });

    console.log('✅ Created agent source: API endpoint');

    // Create sample questions generated by this agent
    const questions = [
      {
        id: 'q-btc-1',
        title: 'Will Bitcoin hit $120k in November 2025?',
        description: 'This question asks whether Bitcoin will reach or exceed $120,000 USD at any point during November 2025. The price will be determined based on major cryptocurrency exchanges including Coinbase, Binance, and Kraken.',
        state: 'published',
        liveDate: new Date('2025-10-28T14:00:00Z'),
        answerEndAt: new Date('2025-11-30T23:59:59Z'),
        settlementAt: new Date('2025-12-05T23:59:59Z'),
        resolutionCriteria: 'Resolves YES if Bitcoin trades at or above $120,000 on any major exchange during November 2025. Resolution will be based on data from Coinbase, Binance, and Kraken.',
        agentId: agent.id,
        aiScore: 0.87,
        type: 'binary',
        poolTotal: 12500.00,
        poolYes: 7800.00,
        poolNo: 4700.00,
        answerCount: 156,
        createdAt: new Date('2025-10-10T10:00:00Z'),
        updatedAt: new Date('2025-10-28T14:00:00Z'),
      },
      {
        id: 'q-btc-2',
        title: 'Will Bitcoin exceed $100,000 in October 2025?',
        description: 'This question asks whether Bitcoin\'s price will reach or exceed $100,000 USD at any point during October 2025. The price will be determined based on major cryptocurrency exchanges including Coinbase, Binance, and Kraken.',
        state: 'pending',
        liveDate: new Date('2025-10-28T16:00:00Z'),
        answerEndAt: new Date('2025-10-25T23:59:59Z'),
        settlementAt: new Date('2025-11-01T23:59:59Z'),
        resolutionCriteria: 'Resolves YES if Bitcoin trades at or above $100,000 on any major exchange during October 2025.',
        agentId: agent.id,
        aiScore: 0.92,
        type: 'binary',
        createdAt: new Date('2025-10-08T14:30:00Z'),
        updatedAt: new Date('2025-10-08T14:30:00Z'),
      },
      {
        id: 'q-btc-3',
        title: 'Will Bitcoin drop below $90k in the next 30 days?',
        description: 'This question asks whether Bitcoin\'s price will fall below $90,000 USD at any point during the next 30 days from the live date. The price will be determined based on major cryptocurrency exchanges.',
        state: 'published',
        liveDate: new Date('2025-10-20T10:00:00Z'),
        answerEndAt: new Date('2025-11-19T23:59:59Z'),
        settlementAt: new Date('2025-11-21T23:59:59Z'),
        resolutionCriteria: 'Resolves YES if Bitcoin trades below $90,000 on any major exchange within 30 days of October 20, 2025.',
        agentId: agent.id,
        aiScore: 0.78,
        type: 'binary',
        poolTotal: 8300.00,
        poolYes: 3200.00,
        poolNo: 5100.00,
        answerCount: 89,
        createdAt: new Date('2025-10-05T08:00:00Z'),
        updatedAt: new Date('2025-10-20T10:00:00Z'),
      },
      {
        id: 'q-btc-4',
        title: 'Will Bitcoin close above $95,000 by the end of Q4 2025?',
        description: 'This question asks whether Bitcoin will have a closing price above $95,000 USD on December 31, 2025. The closing price will be determined at 11:59 PM UTC on the last day of Q4 2025.',
        state: 'published',
        liveDate: new Date('2025-10-15T12:00:00Z'),
        answerEndAt: new Date('2025-12-30T23:59:59Z'),
        settlementAt: new Date('2026-01-02T23:59:59Z'),
        resolutionCriteria: 'Resolves YES if Bitcoin closes above $95,000 on December 31, 2025, at 11:59 PM UTC based on Coinbase data.',
        agentId: agent.id,
        aiScore: 0.85,
        type: 'binary',
        poolTotal: 15200.00,
        poolYes: 9500.00,
        poolNo: 5700.00,
        answerCount: 203,
        createdAt: new Date('2025-10-01T09:00:00Z'),
        updatedAt: new Date('2025-10-15T12:00:00Z'),
      },
      {
        id: 'q-btc-5',
        title: 'Will Bitcoin reach a new all-time high in 2025?',
        description: 'This question asks whether Bitcoin will surpass its previous all-time high price at any point during 2025. The previous ATH was approximately $69,000 reached in November 2021.',
        state: 'resolved',
        liveDate: new Date('2025-01-15T10:00:00Z'),
        answerEndAt: new Date('2025-12-20T23:59:59Z'),
        settlementAt: new Date('2025-12-31T23:59:59Z'),
        resolutionCriteria: 'Resolves YES if Bitcoin exceeds its November 2021 all-time high of ~$69,000 at any point in 2025.',
        agentId: agent.id,
        aiScore: 0.95,
        outcome: 'YES',
        type: 'binary',
        poolTotal: 25600.00,
        poolYes: 18900.00,
        poolNo: 6700.00,
        answerCount: 387,
        createdAt: new Date('2024-12-28T08:00:00Z'),
        updatedAt: new Date('2025-12-31T23:59:59Z'),
      },
    ];

    for (const questionData of questions) {
      const question = await prisma.question.create({
        data: questionData,
      });
      console.log(`✅ Created question: ${question.title.substring(0, 50)}...`);
    }

    console.log('\\n🎉 Successfully seeded Bitcoin Price Feed Agent with 5 sample questions!');
    console.log(`\\nAgent ID: ${agent.id}`);
    console.log(`Agent Name: ${agent.name}`);
    console.log(`Category: ${agent.category}`);
    console.log(`Questions Created: ${questions.length}`);

  } catch (error) {
    console.error('❌ Error seeding data:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run the seed function
seedBTCAgent()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
